### PR TITLE
Check hotswap agent bundle version and updates it if newer version found

### LINKED ISSUE #69: Update hotswap-agent.jar in ~/.vaadin on plugin installation
Currently the hotswap-agent.jar is copied only if the target does not exist. That will not work when we want to update the bundled version.

If we copy it on plugin installation/upgrade, then you have a possibility to the version manually (e.g. for testing) but will need to do it again after upgrading the plugin version

### PR DESCRIPTION
**Pull request by abdullahtellioglu**
## Description

Checks and replaces if the bundled version is a newer version than the hotswapagent.jar in `~/.vaadin` folder 

Fixes #69 

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

File: src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt [hunk 1]
```diff
@@ -27,10 +30,10 @@ object VaadinHomeUtil {
      * @return the hotswap-agent.jar file
      */
     fun getHotswapAgentJar(): File {
-        val hotswapAgentJar = File(intellijFolder, "hotswap-agent.jar")
-        if (!hotswapAgentJar.exists()) {
+        val hotswapAgentJar = File(intellijFolder, HOTSWAP_AGENT_JAR_FILE_NAME)
+        if (!hotswapAgentJar.exists() || this.isBundledVersionNewer()) {
```
[the remark this answers is not in the document]
Comment (abdullahtellioglu) [reply src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt:34]: I moved the version check to `ConfigurationCheckPostStartupProjectActivity` with `RunOnceUtil.runOnceForApp` wrapped. I also added plugin version to id so that version check can be run on version upgrades

File: src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt [hunk 2]
```diff
@@ -43,7 +48,65 @@ object VaadinHomeUtil {
         }
         return hotswapAgentJar;
     }
+    fun checkBundledAndCurrentVersionAndReplaceIfBundledOneIsNewer(){
+        try{
+            val hotswapAgentJar = File(intellijFolder, HOTSWAP_AGENT_JAR_FILE_NAME)
+            val bundledHotswap = this.javaClass.classLoader.getResource(HOTSWAP_AGENT_JAR_FILE_NAME)
+                ?: throw IllegalStateException("The plugin package is broken: no hotswap-agent.jar found");
+            if(isBundledVersionNewer()){
+                IOUtils.copyLarge(bundledHotswap.openStream(), hotswapAgentJar.outputStream())
```
Comment (MarcinVaadin) [inline src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt:57]: There is nice `com.intellij.openapi.util.io.FileUtils` which we might use for files management, no external dependency needed.

Comment (abdullahtellioglu) [reply src/main/kotlin/com/vaadin/plugin/utils/VaadinHomeUtil.kt]: Replaced 👍

**Review by MarcinVaadin — APPROVED** [review]
