### PR TITLE
fix: encode project name

### LINKED ISSUE #63: Unable to create a new app with space in the name
image

### PR DESCRIPTION
**Pull request by MarcinVaadin**
Fixes not encoded project name

Fixes #63

### CODE REVIEW

File: src/main/kotlin/com/vaadin/plugin/starter/QuickStarterModel.kt [hunk 1]
```diff
@@ -25,7 +26,7 @@ class QuickStarterModel(
             preset += "&preset=partial-prerelease"
         }
 
-        return "https://start.vaadin.com/dl?preset=${preset}&projectName=${project.name}"
+        return "https://start.vaadin.com/dl?preset=${preset}&projectName=${URLEncoder.encode(project.name, "UTF-8")}"
```
Comment (Artur-) [inline src/main/kotlin/com/vaadin/plugin/starter/QuickStarterModel.kt:29]: URLEncoder.encode does not encode for query parameters but maybe it works here. Typically people suggest adding `replace("+","%20")` to make it more correct

**Review by Artur- — APPROVED** [review]
